# Generated by Django 4.1.7 on 2023-04-08 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0002_alter_caseitem_drop_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("uses", models.PositiveIntegerField(default=1)),
                (
                    "promo_type",
                    models.CharField(
                        choices=[("item", "item"), ("money", "money")], max_length=10
                    ),
                ),
                ("amount", models.SmallIntegerField(blank=True, null=True)),
                ("items", models.ManyToManyField(blank=True, to="cases.item")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
