# Generated by Django 4.1.7 on 2023-04-10 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_remove_bonuscode_percentage_remove_bonuscode_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("uses", models.IntegerField(default=-1)),
                ("amount", models.SmallIntegerField(blank=True, null=True)),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="bonuscode",
            name="uses",
            field=models.IntegerField(default=-1),
        ),
    ]
