# Generated by Django 4.1.7 on 2023-05-10 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_promocode_alter_bonuscode_uses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="amount",
        ),
    ]
