# Generated by Django 4.1.7 on 2023-12-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0015_item_description"),
        ("custom_user", "0010_remove_customuser_photo_url_customuser_photo"),
        ("payments", "0004_remove_promocode_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom_user.customuser",
                    ),
                ),
            ],
        ),
    ]
