version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: backend_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0:8000"
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery-worker:
    build: .
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./:/code/
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./:/code/
    depends_on:
      - db
      - redis


volumes:
  db_data:
