# Generated by Django 4.1.7 on 2023-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_alter_caseitem_drop_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cashback",
            field=models.IntegerField(null=True),
        ),
    ]
