# Generated by Django 4.1.7 on 2023-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_item_cashback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[("crystal", "Crystal"), ("moon", "Moon"), ("money", "Money")],
                max_length=10,
            ),
        ),
    ]
