# Generated by Django 4.1.7 on 2023-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_alter_item_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="quantity",
            new_name="crystals",
        ),
    ]
