# Generated by Django 4.1.7 on 2023-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0005_rename_quantity_item_crystals"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="photo_url",
            field=models.ImageField(blank=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="case",
            name="photo_url",
            field=models.ImageField(blank=True, upload_to="cases/"),
        ),
    ]
