# Generated by Django 4.1.7 on 2023-06-03 14:22

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0006_item_photo_url_alter_case_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="category",
            field=models.CharField(
                choices=[
                    ("mondstadt", "Монштадт"),
                    ("liyue", "Ли Юэ"),
                    ("sumeru", "Сумеру"),
                    ("inadzuma", "Инадзума"),
                    ("special", "Специальные"),
                ],
                default="mondstadt",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="photo_url",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
