# Generated by Django 4.1.7 on 2023-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_case_category_alter_case_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="photo_url",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
