# Generated by Django 4.1.7 on 2023-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0009_alter_case_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo_url",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
