# Generated by Django 4.1.7 on 2023-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_alter_case_photo_url_alter_item_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ph_price",
            field=models.IntegerField(default=0),
        ),
    ]
