# Generated by Django 4.1.7 on 2023-04-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("telegram_id", models.PositiveIntegerField(null=True, unique=True)),
                ("vk_id", models.PositiveBigIntegerField(null=True, unique=True)),
                ("genshin_uid", models.PositiveBigIntegerField(blank=True, null=True)),
                ("photo_url", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                (
                    "registration_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("current_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("used_ips", models.TextField(blank=True, default="")),
                (
                    "token",
                    models.CharField(
                        db_index=True, default="", max_length=64, unique=True
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom_user.customuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
