# Generated by Django 4.1.7 on 2023-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
