# Generated by Django 4.1.7 on 2023-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0003_customuser_is_frozen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo_url",
            field=models.TextField(
                blank=True, default="https://vk.com/images/camera_100.png"
            ),
        ),
    ]
