# Generated by Django 4.1.7 on 2023-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0004_alter_customuser_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="vk_access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
