# Generated by Django 4.1.7 on 2023-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0005_customuser_vk_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
