# Generated by Django 4.1.7 on 2023-05-06 20:13

from django.db import migrations, models
import uuid


def set_unique_id(apps, schema_editor):
    CustomUser = apps.get_model('custom_user', 'CustomUser')
    existing_uuids = set(CustomUser.objects.values_list('unique_id', flat=True))

    for user in CustomUser.objects.all():
        new_uuid = uuid.uuid4()
        while new_uuid in existing_uuids:
            new_uuid = uuid.uuid4()

        user.unique_id = new_uuid
        user.save()
        existing_uuids.add(new_uuid)

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0007_alter_customuser_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="password"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="vk_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(set_unique_id, noop),
    ]
