# Generated by Django 4.1.7 on 2023-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0008_customuser_unique_id_alter_customuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="genshin_uid",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telegram_id",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
