# Generated by Django 4.1.7 on 2023-12-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0009_alter_customuser_genshin_uid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
