# Generated by Django 4.1.7 on 2023-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
