# Generated by Django 4.1.7 on 2023-04-17 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_item_is_frozen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="is_frozen",
            new_name="from_shop",
        ),
    ]
