# Generated by Django 4.1.7 on 2023-05-03 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0007_alter_customuser_photo_url"),
        ("orders", "0008_delete_testorders"),
        ("history", "0004_item_real_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Case",
            new_name="HistoryCase",
        ),
        migrations.RenameModel(
            old_name="Item",
            new_name="HistoryItem",
        ),
    ]
