# Generated by Django 4.1.7 on 2023-05-04 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0005_rename_case_historycase_rename_item_historyitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historycase",
            options={"ordering": ["-opened_at"]},
        ),
    ]
