# Generated by Django 4.1.7 on 2023-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0006_alter_historycase_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historyitem",
            old_name="quantity",
            new_name="crystals",
        ),
    ]
