# Generated by Django 4.1.7 on 2023-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0007_rename_quantity_historyitem_crystals"),
    ]

    operations = [
        migrations.AddField(
            model_name="historycase",
            name="photo_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="historyitem",
            name="photo_url",
            field=models.URLField(null=True),
        ),
    ]
