# Generated by Django 4.1.7 on 2023-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0008_historycase_photo_url_historyitem_photo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyitem",
            name="real_name",
        ),
        migrations.AddField(
            model_name="historyitem",
            name="ph_price",
            field=models.IntegerField(default=0),
        ),
    ]
