# Generated by Django 4.1.7 on 2023-09-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0013_rename_ph_price_item_sgd_price_alter_case_category"),
        ("history", "0009_remove_historyitem_real_name_historyitem_ph_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historycase",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historycase",
            name="photo_url",
        ),
        migrations.RemoveField(
            model_name="historyitem",
            name="crystals",
        ),
        migrations.RemoveField(
            model_name="historyitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historyitem",
            name="ph_price",
        ),
        migrations.RemoveField(
            model_name="historyitem",
            name="photo_url",
        ),
        migrations.RemoveField(
            model_name="historyitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="historyitem",
            name="type",
        ),
        migrations.AddField(
            model_name="historycase",
            name="case",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cases.case"
            ),
        ),
        migrations.AddField(
            model_name="historyitem",
            name="item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cases.item"
            ),
        ),
    ]
