# Generated by Django 4.1.7 on 2023-07-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("custom_user", "0009_alter_customuser_genshin_uid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("DEBUG", "Debug"),
                            ("INFO", "Information"),
                            ("WARN", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("http_method", models.CharField(blank=True, max_length=10, null=True)),
                ("response_status_code", models.PositiveSmallIntegerField(default=200)),
                ("error_details", models.CharField(max_length=200)),
                ("additional", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom_user.customuser",
                    ),
                ),
            ],
        ),
    ]
