# Generated by Django 4.1.7 on 2023-04-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("custom_user", "0002_customuser_balance"),
        ("cases", "0002_alter_caseitem_drop_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Giveaway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GiveawayPermissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("account_age_days", "Account age in days"),
                            (
                                "coins_purchased_week",
                                "Coins purchased in the last week",
                            ),
                            (
                                "telegram_channel_subscription",
                                "Telegram channel subscription",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "giveaway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="giveaways.giveaway",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiveawayItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "giveaway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giveaways.giveaway",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("giveaway", "item")},
            },
        ),
        migrations.AddField(
            model_name="giveaway",
            name="items",
            field=models.ManyToManyField(
                blank=True, through="giveaways.GiveawayItem", to="cases.item"
            ),
        ),
        migrations.AddField(
            model_name="giveaway",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_giveaways",
                to="custom_user.customuser",
            ),
        ),
        migrations.AddField(
            model_name="giveaway",
            name="permission_rules",
            field=models.ManyToManyField(
                blank=True,
                related_name="giveaways",
                to="giveaways.giveawaypermissionrule",
            ),
        ),
        migrations.AddField(
            model_name="giveaway",
            name="winners",
            field=models.ManyToManyField(
                blank=True, related_name="won_giveaways", to="custom_user.customuser"
            ),
        ),
    ]
