# Generated by Django 4.1.7 on 2023-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveaway",
            name="is_stopped",
            field=models.BooleanField(default=False),
        ),
    ]
