# Generated by Django 4.1.7 on 2023-04-12 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0002_giveaway_is_stopped"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giveaway",
            name="is_stopped",
        ),
    ]
