# Generated by Django 4.1.7 on 2023-04-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_balance"),
        ("cases", "0002_alter_caseitem_drop_rate"),
        ("giveaways", "0003_remove_giveaway_is_stopped"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giveaway",
            name="winners",
        ),
        migrations.CreateModel(
            name="GiveawayWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "giveaway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giveaways.giveaway",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.item"
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_user.customuser",
                    ),
                ),
            ],
        ),
    ]
