# Generated by Django 4.1.7 on 2023-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0004_remove_giveaway_winners_giveawaywinner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giveaway",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
