# Generated by Django 4.1.7 on 2023-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_balance"),
        ("giveaways", "0005_alter_giveaway_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveaway",
            name="winners",
            field=models.ManyToManyField(
                blank=True,
                related_name="won_giveaways",
                through="giveaways.GiveawayWinner",
                to="custom_user.customuser",
            ),
        ),
    ]
