# Generated by Django 4.1.7 on 2023-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_balance"),
        ("giveaways", "0007_giveaway_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveawayitem",
            name="winners",
            field=models.ManyToManyField(
                blank=True, related_name="won_items", to="custom_user.customuser"
            ),
        ),
    ]
