# Generated by Django 4.1.7 on 2023-04-13 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0008_giveawayitem_winners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giveaway",
            name="winners",
        ),
        migrations.DeleteModel(
            name="GiveawayWinner",
        ),
    ]
