# Generated by Django 4.1.7 on 2023-04-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_balance"),
        ("giveaways", "0009_remove_giveaway_winners_delete_giveawaywinner"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveaway",
            name="type",
            field=models.CharField(
                choices=[("normal", "Normal"), ("lottery", "Lottery")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="LotteryTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets", models.IntegerField()),
                (
                    "giveaway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giveaways.giveaway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_user.customuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "giveaway")},
            },
        ),
    ]
