# Generated by Django 4.1.7 on 2023-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0010_giveaway_type_lotteryticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotteryticket",
            name="tickets",
            field=models.IntegerField(default=11),
        ),
    ]
