# Generated by Django 4.1.7 on 2023-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0011_alter_lotteryticket_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotteryticket",
            name="tickets",
            field=models.IntegerField(default=1),
        ),
    ]
