# Generated by Django 4.1.7 on 2023-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0012_alter_lotteryticket_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giveawaypermissionrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("account_age_days", "Account age in days"),
                    ("coins_purchased_week", "Coins purchased in the last week"),
                    ("telegram_channel_subscription", "Telegram channel subscription"),
                    ("vk_channel_subscription", "VK channel subscription"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="giveawaypermissionrule",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
