# Generated by Django 4.1.7 on 2023-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0013_alter_giveawaypermissionrule_rule_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveawaypermissionrule",
            name="text_value",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="giveawaypermissionrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("account_age_days", "Account age in days"),
                    ("coins_purchased_week", "Coins purchased in the last week"),
                    ("telegram_channel_subscription", "Telegram channel subscription"),
                    ("vk_channel_subscription", "VK channel subscription"),
                    ("vk_wallpost", "VK wall post"),
                ],
                max_length=50,
            ),
        ),
    ]
