# Generated by Django 4.1.7 on 2023-04-30 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0014_giveawaypermissionrule_text_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giveaway",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 1, 12, 51, 55, 637392, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
