# Generated by Django 4.1.7 on 2023-04-30 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0015_alter_giveaway_end_time_alter_giveaway_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giveaway",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 1, 13, 28, 50, 705610, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
