# Generated by Django 4.1.7 on 2023-05-03 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0016_alter_giveaway_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giveaway",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 4, 20, 25, 50, 561101, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
