# Generated by Django 4.1.7 on 2023-05-07 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("giveaways", "0019_alter_giveaway_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giveawaypermissionrule",
            name="giveaway",
        ),
    ]
