# Generated by Django 4.1.7 on 2023-04-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("fulfilled_at", models.DateTimeField(null=True)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("withdrawing", "Withdrawing"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="history.item"
                    ),
                ),
            ],
        ),
    ]
