# Generated by Django 4.1.7 on 2023-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="step",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("withdrawing", "Withdrawing"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="processing",
                max_length=11,
                null=True,
            ),
        ),
    ]
