# Generated by Django 4.1.7 on 2023-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_orders_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
