# Generated by Django 4.1.7 on 2023-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_orders_fulfilled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="step",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("withdrawing", "Withdrawing"),
                    ("withdrawn", "Withdrawn"),
                    ("declined", "Declined"),
                ],
                default="processing",
                max_length=11,
                null=True,
            ),
        ),
    ]
