# Generated by Django 4.1.7 on 2023-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_orders_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="is_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="step",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("withdrawing", "Withdrawing"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="processing",
                max_length=11,
                null=True,
            ),
        ),
    ]
