# Generated by Django 4.1.7 on 2023-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_orders_is_allowed_alter_orders_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="genshin_uid",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
