# Generated by Django 4.1.7 on 2023-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orders_genshin_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestOrders",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.orders",),
        ),
        migrations.AddField(
            model_name="orders",
            name="is_test_instance",
            field=models.BooleanField(default=False),
        ),
    ]
