# Generated by Django 4.1.7 on 2023-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_delete_testorders"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("default_payment", models.IntegerField(default=2000)),
                ("total_balance", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="is_in_queue",
            field=models.BooleanField(default=False),
        ),
    ]
