# Generated by Django 4.1.7 on 2023-08-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_balance_orders_is_in_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("wallet_address", models.TextField()),
                ("default_payment", models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Balance",
        ),
    ]
